// Auto-generated by build/bundle-assets.ps1 - DO NOT EDIT DIRECTLY. 
// Edit the individual sofia-*.* source files in wwwroot/ instead; this file 
// is regenerated on every build. 

// ===== sofia-animateonscroll.js ===== 
window.sofiaAnimateOnScroll = {
    _instances: {},
    _scrollY: typeof window !== "undefined" ? window.scrollY || 0 : 0,
    _direction: "down",
    _scrollBound: false,

    _ensureScrollTracker: function () {
        if (this._scrollBound || typeof window === "undefined") {
            return;
        }

        var self = this;
        this._scrollBound = true;
        this._scrollY = window.scrollY || window.pageYOffset || 0;

        window.addEventListener(
            "scroll",
            function () {
                var y = window.scrollY || window.pageYOffset || 0;
                // Deadzone avoids direction flicker on tiny scroll jitter.
                if (y > self._scrollY + 10) {
                    self._direction = "down";
                } else if (y < self._scrollY - 10) {
                    self._direction = "up";
                }
                self._scrollY = y;
            },
            { passive: true }
        );
    },

    _split: function (className) {
        if (!className || typeof className !== "string") {
            return [];
        }

        return className.split(/\s+/).filter(Boolean);
    },

    _addClass: function (el, className) {
        this._split(className).forEach(function (c) {
            el.classList.add(c);
        });
    },

    _removeClass: function (el, className) {
        this._split(className).forEach(function (c) {
            el.classList.remove(c);
        });
    },

    _applyDirection: function (el, direction) {
        el.classList.remove("sofia-aos--dir-up", "sofia-aos--dir-down");
        el.classList.add(direction === "up" ? "sofia-aos--dir-up" : "sofia-aos--dir-down");
        el.setAttribute("data-aos-dir", direction);
    },

    _directionFromEntry: function (entry, isEntering) {
        var rootBottom = window.innerHeight || document.documentElement.clientHeight || 0;
        var top = entry.boundingClientRect.top;
        var bottom = entry.boundingClientRect.bottom;

        if (isEntering) {
            if (bottom <= 0) {
                return "up";
            }
            if (top >= rootBottom) {
                return "down";
            }
            return top > rootBottom * 0.4 ? "down" : this._direction;
        }

        if (bottom <= 0 || top < 0) {
            return "down";
        }
        if (top >= rootBottom) {
            return "up";
        }

        return this._direction;
    },

    observe: function (element, dotNetRef, options) {
        if (!element || typeof IntersectionObserver === "undefined") {
            return null;
        }

        this._ensureScrollTracker();

        options = options || {};
        var self = this;
        var enterClass = options.enterClass || "";
        var leaveClass = options.leaveClass || "";
        var once = !!options.once;
        // Slight inset so edges don't flicker; keep stable (no dynamic changes).
        var rootMargin = options.rootMargin || "0px 0px -6% 0px";
        var root = null;

        // Hysteresis: must reach enterAt to show, must fall to leaveAt to hide.
        var enterAt = options.enterThreshold != null ? options.enterThreshold : 0.28;
        var leaveAt = options.leaveThreshold != null ? options.leaveThreshold : 0.06;
        if (leaveAt >= enterAt) {
            leaveAt = Math.max(0, enterAt * 0.25);
        }

        if (options.rootSelector) {
            root = document.querySelector(options.rootSelector);
        }

        if (root) {
            var lastTop = root.scrollTop || 0;
            root.addEventListener(
                "scroll",
                function () {
                    var top = root.scrollTop || 0;
                    if (top > lastTop + 10) {
                        self._direction = "down";
                    } else if (top < lastTop - 10) {
                        self._direction = "up";
                    }
                    lastTop = top;
                },
                { passive: true }
            );
        }

        var id = "aos-" + Math.random().toString(36).slice(2);
        var animationState = enterClass ? "hidden" : "visible";
        var isShown = !enterClass;
        var busy = false;
        var cooldownUntil = 0;
        var lastEntry = null;
        var pendingShown = null;
        var animationEndListener;
        var observer;
        var cooldownTimer;

        if (enterClass) {
            element.style.opacity = "0";
            element.classList.add("sofia-aos--pending");
        }

        function now() {
            return typeof performance !== "undefined" && performance.now
                ? performance.now()
                : Date.now();
        }

        function isBusy() {
            return busy || now() < cooldownUntil;
        }

        function unbindAnimationEvents() {
            if (animationEndListener) {
                element.removeEventListener("animationend", animationEndListener);
                animationEndListener = undefined;
            }
        }

        function startCooldown(ms) {
            cooldownUntil = now() + (ms || 140);
            if (cooldownTimer) {
                clearTimeout(cooldownTimer);
            }
            cooldownTimer = setTimeout(function () {
                cooldownTimer = null;
                flushPending();
            }, (ms || 140) + 16);
        }

        function bindAnimationEvents(onEnd) {
            unbindAnimationEvents();
            animationEndListener = function (ev) {
                if (ev.target !== element) {
                    return;
                }

                // Ignore child / leftover animation names.
                var name = ev.animationName || "";
                if (
                    name &&
                    name.indexOf("sofia-aos-enter") < 0 &&
                    name.indexOf("sofia-aos-leave") < 0
                ) {
                    return;
                }

                self._removeClass(element, enterClass);
                self._removeClass(element, leaveClass);
                busy = false;
                if (typeof onEnd === "function") {
                    onEnd();
                }
                unbindAnimationEvents();
                startCooldown(160);
            };
            element.addEventListener("animationend", animationEndListener);
        }

        function enter(direction) {
            if (!enterClass || isShown || animationState === "enter") {
                return;
            }

            // Never interrupt a leave mid-flight; queue instead.
            if (busy) {
                pendingShown = true;
                return;
            }

            busy = true;
            pendingShown = null;
            self._applyDirection(element, direction || self._direction);
            element.classList.remove("sofia-aos--pending");
            element.style.opacity = "";
            self._removeClass(element, leaveClass);
            void element.offsetWidth;
            self._addClass(element, enterClass);

            if (once && observer) {
                observer.unobserve(element);
            }

            animationState = "enter";
            isShown = true;

            bindAnimationEvents(function () {
                element.style.opacity = "1";
                animationState = "visible";
            });

            if (dotNetRef) {
                try {
                    dotNetRef.invokeMethodAsync("NotifyEnter");
                } catch (_) {
                    /* ignore */
                }
            }
        }

        function leave(direction) {
            if (!isShown || animationState === "leave" || animationState === "hidden") {
                return;
            }

            if (busy) {
                pendingShown = false;
                return;
            }

            if (!leaveClass) {
                element.style.opacity = enterClass ? "0" : "";
                element.classList.add("sofia-aos--pending");
                animationState = "hidden";
                isShown = false;
                startCooldown(120);
                return;
            }

            busy = true;
            pendingShown = null;
            self._applyDirection(element, direction || self._direction);
            self._removeClass(element, enterClass);
            element.style.opacity = "1";
            void element.offsetWidth;
            self._addClass(element, leaveClass);

            animationState = "leave";
            isShown = false;

            bindAnimationEvents(function () {
                element.style.opacity = "0";
                element.classList.add("sofia-aos--pending");
                animationState = "hidden";
            });

            if (dotNetRef) {
                try {
                    dotNetRef.invokeMethodAsync("NotifyLeave");
                } catch (_) {
                    /* ignore */
                }
            }
        }

        function desiredFromEntry(entry) {
            if (!entry) {
                return isShown;
            }

            var ratio = entry.intersectionRatio || 0;
            if (!entry.isIntersecting) {
                ratio = 0;
            }

            // Hysteresis band between leaveAt and enterAt prevents threshold chatter.
            if (isShown) {
                return ratio > leaveAt;
            }

            return ratio >= enterAt;
        }

        function flushPending() {
            if (isBusy()) {
                return;
            }

            var want = pendingShown;
            if (want === null && lastEntry) {
                want = desiredFromEntry(lastEntry);
            }

            if (want === null || want === isShown) {
                pendingShown = null;
                return;
            }

            pendingShown = null;
            var dir = self._direction;
            if (lastEntry) {
                dir = self._direction || self._directionFromEntry(lastEntry, want);
            }

            if (want) {
                enter(dir);
            } else {
                leave(dir);
            }
        }

        function onIntersect(entry) {
            lastEntry = entry;
            var want = desiredFromEntry(entry);

            if (want === isShown) {
                pendingShown = null;
                return;
            }

            if (isBusy()) {
                // Remember intent; apply only after animation/cooldown settles.
                pendingShown = want;
                return;
            }

            var dir = self._direction || self._directionFromEntry(entry, want);
            if (want) {
                enter(dir);
            } else {
                leave(dir);
            }
        }

        observer = new IntersectionObserver(
            function (entries) {
                var entry = entries[0];
                if (!entry) {
                    return;
                }
                onIntersect(entry);
            },
            {
                root: root,
                rootMargin: rootMargin,
                // Dense thresholds so ratio updates smoothly for hysteresis.
                threshold: [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5, 0.65, 0.8, 1]
            }
        );

        setTimeout(function () {
            observer.observe(element);
        }, 0);

        this._instances[id] = {
            element: element,
            observer: observer,
            unbindAnimationEvents: unbindAnimationEvents,
            clearCooldown: function () {
                if (cooldownTimer) {
                    clearTimeout(cooldownTimer);
                    cooldownTimer = null;
                }
            }
        };

        return id;
    },

    unobserve: function (id) {
        var instance = this._instances[id];
        if (!instance) {
            return;
        }

        try {
            instance.unbindAnimationEvents();
            instance.clearCooldown();
            instance.observer.unobserve(instance.element);
            instance.observer.disconnect();
        } catch (_) {
            /* ignore */
        }

        delete this._instances[id];
    }
};


// ===== sofia-carousel.js ===== 
window.sofiaCarousel = {
    measureOffsets: function (viewport, track, vertical) {
        if (!viewport || !track) {
            return { viewport: 0, offsets: [], sizes: [] };
        }

        var vRect = viewport.getBoundingClientRect();
        var viewportSize = vertical ? vRect.height : vRect.width;
        var items = track.children || [];
        var offsets = [];
        var sizes = [];

        for (var i = 0; i < items.length; i++) {
            offsets.push(vertical ? items[i].offsetTop : items[i].offsetLeft);
            sizes.push(vertical ? items[i].offsetHeight : items[i].offsetWidth);
        }

        return { viewport: viewportSize, offsets: offsets, sizes: sizes };
    }
};


// ===== sofia-color.js ===== 
window.sofiaColor = {
  getRect: function (element) {
    if (!element) {
      return { width: 0, height: 0, left: 0, top: 0 };
    }

    var rect = element.getBoundingClientRect();
    return {
      width: rect.width,
      height: rect.height,
      left: rect.left,
      top: rect.top
    };
  },

  eyeDropperPick: async function () {
    if (!window.EyeDropper) {
      return null;
    }

    try {
      var dropper = new window.EyeDropper();
      var result = await dropper.open();
      return result && result.sRGBHex ? result.sRGBHex : null;
    } catch (e) {
      return null;
    }
  }
};

// Back-compat alias used by early drafts.
window.sofiaEyeDropperPick = function () {
  return window.sofiaColor.eyeDropperPick();
};


// ===== sofia-commandmenu.js ===== 
window.sofiaCommandMenu = {
    _handlers: {},

    registerHotkey: function (dotNetRef) {
        if (!dotNetRef) {
            return null;
        }

        var id =
            typeof crypto !== "undefined" && crypto.randomUUID
                ? crypto.randomUUID()
                : "cm-" + Date.now() + "-" + Math.random().toString(36).slice(2);

        var handler = function (e) {
            var key = (e.key || "").toLowerCase();
            if (key === "k" && (e.metaKey || e.ctrlKey)) {
                e.preventDefault();
                dotNetRef.invokeMethodAsync("ToggleFromHotkey");
            }
        };

        document.addEventListener("keydown", handler);
        this._handlers[id] = handler;
        return id;
    },

    unregisterHotkey: function (id) {
        var handler = this._handlers[id];
        if (!handler) {
            return;
        }

        document.removeEventListener("keydown", handler);
        delete this._handlers[id];
    }
};


// ===== sofia-compare.js ===== 
window.sofiaCompare = {
    measure: function (element, vertical) {
        if (!element || typeof element.getBoundingClientRect !== "function") {
            return { size: 0, start: 0 };
        }

        var rect = element.getBoundingClientRect();
        return vertical
            ? { size: rect.height, start: rect.top }
            : { size: rect.width, start: rect.left };
    },

    capture: function (element, pointerId) {
        if (!element || typeof element.setPointerCapture !== "function") {
            return;
        }

        try {
            element.setPointerCapture(pointerId);
        } catch (_) {
            /* ignore */
        }
    },

    release: function (element, pointerId) {
        if (!element || typeof element.releasePointerCapture !== "function") {
            return;
        }

        try {
            element.releasePointerCapture(pointerId);
        } catch (_) {
            /* ignore */
        }
    }
};


// ===== sofia-datagrid-wf.js ===== 
window.sofiaDataGridWf = {
    _handlers: {},

    isReady: function () {
        return true;
    },

    _overlaySelector: ".sofia-select--open, .sofia-datepicker--open, .sofia-select__popup, .sofia-datepicker__panel",

    _isOverlayNavKey: function (key) {
        return key === "ArrowUp"
            || key === "ArrowDown"
            || key === "ArrowLeft"
            || key === "ArrowRight"
            || key === "PageUp"
            || key === "PageDown"
            || key === "Home"
            || key === "End"
            || key === "Enter"
            || key === "NumpadEnter"
            || key === " "
            || key === "Spacebar";
    },

    _isOverlayOpen: function (target) {
        return !!(target && target.closest && target.closest(this._overlaySelector));
    },

    /** Text inputs keep ↑/↓ (caret / spinner). Select triggers & readonly date fields yield to row nav. */
    _editorKeepsVerticalArrows: function (target) {
        if (!target) {
            return false;
        }

        var tag = (target.tagName || "").toUpperCase();
        if (tag === "TEXTAREA") {
            return true;
        }

        if (tag === "SELECT") {
            return true;
        }

        if (tag === "INPUT") {
            var type = (target.type || "text").toLowerCase();
            if (type === "checkbox" || type === "radio" || type === "button" || type === "submit" || type === "reset") {
                return false;
            }

            // Readonly datepicker field: arrows move between rows.
            if (target.readOnly || target.disabled) {
                return false;
            }

            return true;
        }

        return false;
    },

    _focusCellEditor: function (cell) {
        if (!cell) {
            return;
        }

        var el = cell.querySelector(
            "input:not([disabled]):not([type='hidden'])," +
            "button.sofia-select__trigger:not([disabled])," +
            "textarea:not([disabled])," +
            "select:not([disabled])," +
            "[tabindex]:not([tabindex='-1'])"
        );
        if (el && typeof el.focus === "function") {
            el.focus();
        }
    },

    _navigateVertical: function (root, cell, delta) {
        var row = cell.closest("[data-sofia-wf-rowkey]");
        if (!row || !root) {
            return;
        }

        var rows = Array.prototype.slice.call(root.querySelectorAll("[data-sofia-wf-rowkey]"));
        var rowIndex = rows.indexOf(row);
        if (rowIndex < 0) {
            return;
        }

        var nextRow = rows[rowIndex + delta];
        if (!nextRow) {
            return;
        }

        var cells = row.querySelectorAll("[data-sofia-wf-cell]");
        var colIndex = Array.prototype.indexOf.call(cells, cell);
        if (colIndex < 0) {
            colIndex = 0;
        }

        var nextCells = nextRow.querySelectorAll("[data-sofia-wf-cell]");
        var nextCell = nextCells[colIndex] || nextCells[0];
        this._focusCellEditor(nextCell);
    },

    bind: function (id, root, dotNetRef) {
        this.unbind(id);
        if (!root) {
            return;
        }

        var self = this;
        var handler = function (e) {
            var cell = e.target && e.target.closest ? e.target.closest("[data-sofia-wf-cell]") : null;
            if (!cell || !root.contains(cell)) {
                return;
            }

            var rowKey = cell.getAttribute("data-sofia-wf-row");
            if (!rowKey) {
                return;
            }

            // Popup open: control owns keys; block browser scroll of the grid underneath.
            if (self._isOverlayOpen(e.target)) {
                if (self._isOverlayNavKey(e.key)) {
                    e.preventDefault();
                }
                return;
            }

            // Closed: ↑/↓ move focus to the same column on the adjacent row.
            if (e.key === "ArrowUp" || e.key === "ArrowDown") {
                if (self._editorKeepsVerticalArrows(e.target)) {
                    return;
                }

                e.preventDefault();
                e.stopPropagation();
                self._navigateVertical(root, cell, e.key === "ArrowDown" ? 1 : -1);
                return;
            }

            var isLast = cell.getAttribute("data-sofia-wf-last") === "true";
            var isEnter = e.key === "Enter" || e.key === "NumpadEnter";
            var isSubmitTab = e.key === "Tab" && !e.shiftKey && isLast;

            if (!isEnter && !isSubmitTab) {
                return;
            }

            e.preventDefault();
            e.stopPropagation();
            dotNetRef.invokeMethodAsync("NotifyWindowsFormSubmit", rowKey);
        };

        this._handlers[id] = { root: root, handler: handler, dotNetRef: dotNetRef };
        root.addEventListener("keydown", handler, true);
    },

    unbind: function (id) {
        var entry = this._handlers[id];
        if (!entry) {
            return;
        }

        entry.root.removeEventListener("keydown", entry.handler, true);
        delete this._handlers[id];
    },

    focusFirstEditor: function (rowEl) {
        if (!rowEl) {
            return;
        }

        var el = rowEl.querySelector(
            ".sofia-datatable__cell-edit input:not([disabled]):not([type='hidden'])," +
            ".sofia-datatable__cell-edit button.sofia-select__trigger:not([disabled])," +
            ".sofia-datatable__cell-edit textarea:not([disabled])," +
            ".sofia-datatable__cell-edit select:not([disabled])," +
            ".sofia-datatable__cell-edit [tabindex]:not([tabindex='-1'])"
        );
        if (el && typeof el.focus === "function") {
            el.focus();
        }
    },

    focusRowEditor: function (root, rowKey, columnIndex) {
        if (!root) {
            return;
        }

        var safeKey = String(rowKey).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
        var row = root.querySelector('[data-sofia-wf-rowkey="' + safeKey + '"]');
        if (!row) {
            return;
        }

        var cells = row.querySelectorAll("[data-sofia-wf-cell]");
        var cell = cells[columnIndex] || cells[0];
        if (!cell) {
            this.focusFirstEditor(row);
            return;
        }

        this._focusCellEditor(cell);
    }
};


// ===== sofia-dialog.js ===== 
window.sofiaDialog = (function () {
    "use strict";

    var sessions = typeof WeakMap !== "undefined" ? new WeakMap() : null;
    var fallbackSessions = [];

    function ensureInteractiveStyles() {
        if (typeof document === "undefined" || document.getElementById("sofia-dialog-interactive-css")) {
            return;
        }

        var style = document.createElement("style");
        style.id = "sofia-dialog-interactive-css";
        style.textContent =
            "html.sofia-dialog--interacting,html.sofia-dialog--interacting *{" +
            "user-select:none!important;-webkit-user-select:none!important;}" +
            "html.sofia-dialog--interacting{cursor:grabbing!important;}" +
            "html.sofia-dialog--resizing,html.sofia-dialog--resizing *{cursor:nwse-resize!important;}" +
            "html.sofia-dialog--interacting iframe{pointer-events:none!important;}" +
            ".sofia-dialog__panel--pinned{" +
            "position:fixed!important;margin:0!important;" +
            "right:auto!important;bottom:auto!important;max-width:none!important;max-height:none!important;}";
        document.head.appendChild(style);
    }

    ensureInteractiveStyles();

    function setBlockScroll(block) {
        if (typeof document === "undefined" || !document.documentElement) {
            return;
        }

        document.documentElement.style.overflow = block ? "hidden" : "";
    }

    function getSession(panel) {
        if (!panel) {
            return null;
        }

        if (sessions) {
            return sessions.get(panel) || null;
        }

        for (var i = 0; i < fallbackSessions.length; i++) {
            if (fallbackSessions[i].panel === panel) {
                return fallbackSessions[i];
            }
        }

        return null;
    }

    function setSession(panel, state) {
        if (!panel) {
            return;
        }

        if (sessions) {
            sessions.set(panel, state);
            return;
        }

        for (var i = 0; i < fallbackSessions.length; i++) {
            if (fallbackSessions[i].panel === panel) {
                fallbackSessions[i] = state;
                return;
            }
        }

        fallbackSessions.push(state);
    }

    function deleteSession(panel) {
        if (!panel) {
            return;
        }

        if (sessions) {
            sessions.delete(panel);
            return;
        }

        fallbackSessions = fallbackSessions.filter(function (s) {
            return s.panel !== panel;
        });
    }

    function roundCssPx(value) {
        var dpr = window.devicePixelRatio || 1;
        return Math.round(value * dpr) / dpr;
    }

    function isInteractiveTarget(target) {
        if (!target || typeof target.closest !== "function") {
            return false;
        }

        return !!target.closest(
            "button, a, input, textarea, select, option, label, [data-sofia-no-drag], [contenteditable='true']"
        );
    }

    function setInteracting(resizing) {
        if (!document.documentElement) {
            return;
        }

        document.documentElement.classList.add("sofia-dialog--interacting");
        document.documentElement.classList.toggle("sofia-dialog--resizing", !!resizing);
    }

    function clearInteracting() {
        if (!document.documentElement) {
            return;
        }

        document.documentElement.classList.remove(
            "sofia-dialog--interacting",
            "sofia-dialog--resizing"
        );
    }

    function capture(el, pointerId) {
        if (!el || typeof el.setPointerCapture !== "function") {
            return;
        }

        try {
            el.setPointerCapture(pointerId);
        } catch (_) {
            /* ignore */
        }
    }

    function release(el, pointerId) {
        if (!el || typeof el.releasePointerCapture !== "function") {
            return;
        }

        try {
            el.releasePointerCapture(pointerId);
        } catch (_) {
            /* ignore */
        }
    }

    /**
     * Pin panel to viewport coordinates so flex centering cannot reflow under the cursor.
     */
    function pinPanel(panel, rect) {
        panel.classList.add("sofia-dialog__panel--pinned");
        panel.style.position = "fixed";
        panel.style.left = rect.left + "px";
        panel.style.top = rect.top + "px";
        panel.style.width = rect.width + "px";
        panel.style.height = rect.height + "px";
        panel.style.margin = "0";
        panel.style.right = "auto";
        panel.style.bottom = "auto";
        panel.style.transform = "none";
        panel.style.maxWidth = "none";
        panel.style.maxHeight = "none";
    }

    /**
     * Return panel to document flow and recover a translate() that preserves the visual top-left.
     */
    function unpinToFlow(panel, desiredLeft, desiredTop, desiredW, desiredH) {
        panel.classList.remove("sofia-dialog__panel--pinned");
        panel.style.position = "";
        panel.style.left = "";
        panel.style.top = "";
        panel.style.right = "";
        panel.style.bottom = "";
        panel.style.margin = "";
        panel.style.transform = "none";

        if (desiredW != null && desiredH != null) {
            panel.style.width = desiredW + "px";
            panel.style.height = desiredH + "px";
            panel.style.maxWidth = "100%";
            panel.style.maxHeight = "none";
        }

        // Force layout at the natural flex position, then offset with transform.
        void panel.offsetWidth;
        var natural = panel.getBoundingClientRect();
        var x = roundCssPx(desiredLeft - natural.left);
        var y = roundCssPx(desiredTop - natural.top);

        if (x !== 0 || y !== 0) {
            panel.style.transform = "translate(" + x + "px, " + y + "px)";
        } else {
            panel.style.transform = "";
        }

        return { x: x, y: y };
    }

    function readPinnedBox(panel, active) {
        return {
            left: parseFloat(panel.style.left) || active.left || 0,
            top: parseFloat(panel.style.top) || active.top || 0,
            width: parseFloat(panel.style.width) || active.currentW || 0,
            height: parseFloat(panel.style.height) || active.currentH || 0
        };
    }

    function endActive(state, notify) {
        var active = state.active;
        if (!active) {
            return;
        }

        state.active = null;
        clearInteracting();

        if (state.header) {
            state.header.classList.remove("sofia-dialog__header--dragging");
        }

        release(active.captureEl, active.pointerId);

        var panel = state.panel;
        var box;
        var offset = { x: 0, y: 0 };

        if (active.pinned) {
            box = readPinnedBox(panel, active);
            offset = unpinToFlow(panel, box.left, box.top, box.width, box.height);
        }

        if (!notify || !state.dotNetRef || !active.moved) {
            return;
        }

        try {
            if (active.type === "drag") {
                state.dotNetRef.invokeMethodAsync("OnDragEnd", offset.x, offset.y);
            } else if (active.type === "resize") {
                state.dotNetRef.invokeMethodAsync(
                    "OnResizeEnd",
                    box.width,
                    box.height,
                    offset.x,
                    offset.y
                );
            }
        } catch (_) {
            /* dispose race */
        }
    }

    function ensurePinnedForDrag(state, active, e) {
        if (active.pinned) {
            return;
        }

        var rect = state.panel.getBoundingClientRect();
        pinPanel(state.panel, rect);
        active.pinned = true;
        active.left = rect.left;
        active.top = rect.top;
        active.currentW = rect.width;
        active.currentH = rect.height;
        // Re-base grab so the click point stays under the cursor after pinning.
        active.grabX = e.clientX - rect.left;
        active.grabY = e.clientY - rect.top;
    }

    function onPointerMove(state, e) {
        var active = state.active;
        if (!active || e.pointerId !== active.pointerId) {
            return;
        }

        // Only while primary (left) button remains pressed.
        if ((e.buttons & 1) === 0) {
            endActive(state, true);
            return;
        }

        if (active.type === "drag") {
            var dx = e.clientX - active.startX;
            var dy = e.clientY - active.startY;

            if (!active.moved) {
                if (Math.hypot(dx, dy) < state.dragThreshold) {
                    return;
                }

                active.moved = true;
                if (state.header) {
                    state.header.classList.add("sofia-dialog__header--dragging");
                }

                ensurePinnedForDrag(state, active, e);
            } else if (!active.pinned) {
                ensurePinnedForDrag(state, active, e);
            }

            var left = roundCssPx(e.clientX - active.grabX);
            var top = roundCssPx(e.clientY - active.grabY);
            active.left = left;
            active.top = top;

            // Synchronous update keeps the grab point glued to the cursor.
            state.panel.style.left = left + "px";
            state.panel.style.top = top + "px";
            return;
        }

        if (active.type === "resize") {
            // Size from pinned top-left so the gripped corner tracks the pointer 1:1.
            var w = Math.max(state.minWidth, e.clientX - active.gripOffsetX - active.left);
            var h = Math.max(state.minHeight, e.clientY - active.gripOffsetY - active.top);
            w = roundCssPx(w);
            h = roundCssPx(h);

            if (!active.moved && w === active.originW && h === active.originH) {
                return;
            }

            active.moved = true;
            active.currentW = w;
            active.currentH = h;

            state.panel.style.width = w + "px";
            state.panel.style.height = h + "px";
        }
    }

    function onPointerUp(state, e) {
        var active = state.active;
        if (!active || e.pointerId !== active.pointerId) {
            return;
        }

        endActive(state, true);
    }

    function detachInteractive(panel) {
        var state = getSession(panel);
        if (!state) {
            return;
        }

        endActive(state, false);

        if (state.header && state.onHeaderDown) {
            state.header.removeEventListener("pointerdown", state.onHeaderDown);
        }

        if (state.resizeHandle && state.onResizeDown) {
            state.resizeHandle.removeEventListener("pointerdown", state.onResizeDown);
        }

        if (state.onMove) {
            document.removeEventListener("pointermove", state.onMove, true);
        }

        if (state.onUp) {
            document.removeEventListener("pointerup", state.onUp, true);
            document.removeEventListener("pointercancel", state.onUp, true);
        }

        if (state.onLostCapture) {
            if (state.header) {
                state.header.removeEventListener("lostpointercapture", state.onLostCapture);
            }

            if (state.resizeHandle) {
                state.resizeHandle.removeEventListener(
                    "lostpointercapture",
                    state.onLostCapture
                );
            }
        }

        deleteSession(panel);
    }

    function attachInteractive(panel, dotNetRef, options) {
        if (!panel) {
            return;
        }

        options = options || {};
        detachInteractive(panel);

        var header = panel.querySelector(".sofia-dialog__header--draggable");
        var resizeHandle = panel.querySelector(".sofia-dialog__resize");
        var draggable = options.draggable !== false && !!header;
        var resizable = options.resizable !== false && !!resizeHandle;

        if (!draggable && !resizable) {
            return;
        }

        var state = {
            panel: panel,
            header: header,
            resizeHandle: resizeHandle,
            dotNetRef: dotNetRef,
            minWidth: options.minWidth > 0 ? options.minWidth : 240,
            minHeight: options.minHeight > 0 ? options.minHeight : 160,
            dragThreshold:
                options.dragThreshold >= 0 ? options.dragThreshold : 3,
            active: null
        };

        state.onMove = function (e) {
            onPointerMove(state, e);
        };

        state.onUp = function (e) {
            onPointerUp(state, e);
        };

        state.onLostCapture = function (e) {
            var active = state.active;
            if (!active || e.pointerId !== active.pointerId) {
                return;
            }

            endActive(state, true);
        };

        state.onHeaderDown = function (e) {
            if (!draggable || e.button !== 0 || e.isPrimary === false) {
                return;
            }

            if (panel.classList.contains("sofia-dialog__panel--maximized")) {
                return;
            }

            if (isInteractiveTarget(e.target)) {
                return;
            }

            e.preventDefault();

            var rect = panel.getBoundingClientRect();
            state.active = {
                type: "drag",
                pointerId: e.pointerId,
                captureEl: header,
                startX: e.clientX,
                startY: e.clientY,
                grabX: e.clientX - rect.left,
                grabY: e.clientY - rect.top,
                left: rect.left,
                top: rect.top,
                currentW: rect.width,
                currentH: rect.height,
                pinned: false,
                moved: false
            };

            setInteracting(false);
            capture(header, e.pointerId);
        };

        state.onResizeDown = function (e) {
            if (!resizable || e.button !== 0 || e.isPrimary === false) {
                return;
            }

            if (panel.classList.contains("sofia-dialog__panel--maximized")) {
                return;
            }

            e.preventDefault();
            e.stopPropagation();

            var rect = panel.getBoundingClientRect();
            pinPanel(panel, rect);

            state.active = {
                type: "resize",
                pointerId: e.pointerId,
                captureEl: resizeHandle,
                startX: e.clientX,
                startY: e.clientY,
                left: rect.left,
                top: rect.top,
                originW: rect.width,
                originH: rect.height,
                currentW: rect.width,
                currentH: rect.height,
                // Keep the same point on the handle under the cursor (not only the box corner).
                gripOffsetX: e.clientX - (rect.left + rect.width),
                gripOffsetY: e.clientY - (rect.top + rect.height),
                pinned: true,
                moved: false
            };

            setInteracting(true);
            capture(resizeHandle, e.pointerId);
        };

        if (draggable) {
            header.addEventListener("pointerdown", state.onHeaderDown);
            header.addEventListener("lostpointercapture", state.onLostCapture);
        }

        if (resizable) {
            resizeHandle.addEventListener("pointerdown", state.onResizeDown);
            resizeHandle.addEventListener(
                "lostpointercapture",
                state.onLostCapture
            );
        }

        document.addEventListener("pointermove", state.onMove, true);
        document.addEventListener("pointerup", state.onUp, true);
        document.addEventListener("pointercancel", state.onUp, true);

        setSession(panel, state);
    }

    function mountTaskbar(element) {
        if (!element || typeof document === "undefined" || !document.body) {
            return;
        }

        if (element.parentElement !== document.body) {
            document.body.appendChild(element);
        }

        element.setAttribute("data-sofia-taskbar-mounted", "true");
    }

    function unmountTaskbar(element) {
        if (!element || !element.parentElement) {
            return;
        }

        try {
            element.parentElement.removeChild(element);
        } catch (_) {
            /* ignore */
        }
    }

    return {
        setBlockScroll: setBlockScroll,
        attachInteractive: attachInteractive,
        detachInteractive: detachInteractive,
        mountTaskbar: mountTaskbar,
        unmountTaskbar: unmountTaskbar
    };
})();


// ===== sofia-download.js ===== 
window.sofiaDownload = {
    /**
     * Downloads a file from bytes.
     * Blazor often serializes byte[] as a base64 string — handle that case.
     */
    fromBytes: function (bytes, fileName, contentType) {
        if (typeof bytes === "string") {
            this.fromBase64(bytes, fileName, contentType);
            return;
        }

        var data;
        if (bytes instanceof Uint8Array) {
            data = bytes;
        } else if (Array.isArray(bytes) || (bytes && typeof bytes.length === "number")) {
            data = new Uint8Array(bytes);
        } else {
            console.error("sofiaDownload.fromBytes: unsupported payload", bytes);
            return;
        }

        this._save(data, fileName, contentType);
    },

    /**
     * Downloads a file from a base64 string (preferred from Blazor).
     */
    fromBase64: function (base64, fileName, contentType) {
        if (!base64) {
            console.error("sofiaDownload.fromBase64: empty payload");
            return;
        }

        var binary = atob(base64);
        var len = binary.length;
        var bytes = new Uint8Array(len);
        for (var i = 0; i < len; i++) {
            bytes[i] = binary.charCodeAt(i);
        }

        this._save(bytes, fileName, contentType);
    },

    _save: function (data, fileName, contentType) {
        var blob = new Blob([data], { type: contentType || "application/octet-stream" });
        var url = URL.createObjectURL(blob);
        var a = document.createElement("a");
        a.href = url;
        a.download = fileName || "download";
        a.style.display = "none";
        document.body.appendChild(a);
        a.click();
        a.remove();
        setTimeout(function () {
            URL.revokeObjectURL(url);
        }, 1500);
    }
};


// ===== sofia-dropzone.js ===== 
window.sofiaDropZone = {
    wireZone: function (zone) {
        if (!zone || zone.__sofiaDropZoneWired) {
            return;
        }

        zone.__sofiaDropZoneWired = true;

        zone.addEventListener(
            "dragstart",
            function (event) {
                try {
                    if (event.dataTransfer) {
                        event.dataTransfer.setData("text/plain", "sofia-dropzone");
                        event.dataTransfer.effectAllowed = "move";
                    }
                } catch (_) {
                    /* ignore */
                }
            },
            true
        );

        zone.addEventListener(
            "dragover",
            function (event) {
                event.preventDefault();
                try {
                    if (event.dataTransfer) {
                        event.dataTransfer.dropEffect = "move";
                    }
                } catch (_) {
                    /* ignore */
                }
            },
            true
        );
    },

    unwireZone: function (zone) {
        if (!zone) {
            return;
        }

        zone.__sofiaDropZoneWired = false;
    }
};


// ===== sofia-fileupload.js ===== 
window.sofiaFileUpload = {
    open: function (inputId) {
        var input = document.getElementById(inputId);
        if (input) {
            input.click();
        }
    },

    attachDrop: function (zone, inputId) {
        if (!zone || zone.__sofiaFileUploadBound) {
            return;
        }

        zone.__sofiaFileUploadBound = true;

        var onDragOver = function (e) {
            e.preventDefault();
            e.stopPropagation();
            zone.classList.add("sofia-fileupload--drag");
        };

        var onDragLeave = function (e) {
            if (!zone.contains(e.relatedTarget)) {
                zone.classList.remove("sofia-fileupload--drag");
            }
        };

        var onDrop = function (e) {
            e.preventDefault();
            e.stopPropagation();
            zone.classList.remove("sofia-fileupload--drag");

            var input = document.getElementById(inputId);
            if (!input || !e.dataTransfer || !e.dataTransfer.files || e.dataTransfer.files.length === 0) {
                return;
            }

            try {
                input.files = e.dataTransfer.files;
            } catch (err) {
                var dt = new DataTransfer();
                for (var i = 0; i < e.dataTransfer.files.length; i++) {
                    dt.items.add(e.dataTransfer.files[i]);
                }
                input.files = dt.files;
            }

            input.dispatchEvent(new Event("change", { bubbles: true }));
        };

        zone.addEventListener("dragenter", onDragOver);
        zone.addEventListener("dragover", onDragOver);
        zone.addEventListener("dragleave", onDragLeave);
        zone.addEventListener("drop", onDrop);
    }
};


// ===== sofia-focustrap.js ===== 
window.sofiaFocusTrap = {
    _instances: {},

    _focusableSelector:
        'a[href], area[href], button:not([disabled]), input:not([disabled]):not([type="hidden"]), select:not([disabled]), textarea:not([disabled]), iframe, object, embed, [contenteditable="true"], [tabindex]:not([tabindex="-1"])',

    _isVisible: function (el) {
        if (!el || el.getAttribute("aria-hidden") === "true") {
            return false;
        }

        var style = window.getComputedStyle(el);
        if (style.visibility === "hidden" || style.display === "none") {
            return false;
        }

        return el.getClientRects().length > 0;
    },

    _getFocusable: function (root) {
        if (!root) {
            return [];
        }

        return Array.prototype.slice
            .call(root.querySelectorAll(this._focusableSelector))
            .filter(function (el) {
                return window.sofiaFocusTrap._isVisible(el);
            });
    },

    _focusInitial: function (state) {
        if (!state || !state.element || !state.trapped) {
            return;
        }

        var target = null;
        if (state.options.initialFocusSelector) {
            target = state.element.querySelector(state.options.initialFocusSelector);
        }

        if (!target) {
            target = state.element.querySelector("[data-autofocus], [data-p-autofocus]");
        }

        if (!target || !this._isVisible(target)) {
            var list = this._getFocusable(state.element);
            target = list.length ? list[0] : null;
        }

        if (target && typeof target.focus === "function") {
            try {
                target.focus({ preventScroll: true });
            } catch (_) {
                target.focus();
            }
        }
    },

    _onKeyDown: function (state, e) {
        if (!state || !state.trapped) {
            return;
        }

        if (e.key === "Escape" || e.key === "Esc") {
            if (state.dotNetRef) {
                state.dotNetRef.invokeMethodAsync("NotifyEscape");
            }
            return;
        }

        if (e.key !== "Tab") {
            return;
        }

        var focusable = this._getFocusable(state.element);
        if (!focusable.length) {
            e.preventDefault();
            return;
        }

        var first = focusable[0];
        var last = focusable[focusable.length - 1];
        var active = document.activeElement;

        if (e.shiftKey) {
            if (active === first || !state.element.contains(active)) {
                e.preventDefault();
                last.focus();
            }
        } else if (active === last || !state.element.contains(active)) {
            e.preventDefault();
            first.focus();
        }
    },

    attach: function (element, dotNetRef, options) {
        if (!element) {
            return null;
        }

        var id =
            typeof crypto !== "undefined" && crypto.randomUUID
                ? crypto.randomUUID()
                : "ft-" + Date.now() + "-" + Math.random().toString(36).slice(2);

        var self = this;
        var state = {
            element: element,
            dotNetRef: dotNetRef,
            options: options || {},
            trapped: options && options.trapped === false ? false : true
        };

        state.keyHandler = function (e) {
            self._onKeyDown(state, e);
        };

        element.addEventListener("keydown", state.keyHandler);
        this._instances[id] = state;

        if (state.trapped && options && options.autoFocus !== false) {
            // Defer so Blazor finishes rendering focusable children.
            requestAnimationFrame(function () {
                self._focusInitial(state);
            });
        }

        return id;
    },

    update: function (id, options) {
        var state = this._instances[id];
        if (!state) {
            return;
        }

        var prev = state.trapped;
        state.options = Object.assign({}, state.options, options || {});
        state.trapped = state.options.trapped === false ? false : true;

        if (state.trapped && !prev && state.options.autoFocus !== false) {
            var self = this;
            requestAnimationFrame(function () {
                self._focusInitial(state);
            });
        }
    },

    dispose: function (id) {
        var state = this._instances[id];
        if (!state) {
            return;
        }

        if (state.element && state.keyHandler) {
            state.element.removeEventListener("keydown", state.keyHandler);
        }

        delete this._instances[id];
    }
};


// ===== sofia-gallery.js ===== 
window.sofiaGallery = {
    setBodyScrollLocked: function (locked) {
        try {
            document.body.style.overflow = locked ? "hidden" : "";
        } catch (_) {
            /* ignore */
        }
    },

    download: function (url, fileName) {
        if (!url) {
            return;
        }

        try {
            var link = document.createElement("a");
            link.href = url;
            link.download = fileName || "image";
            link.target = "_blank";
            link.rel = "noopener noreferrer";
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        } catch (_) {
            window.open(url, "_blank", "noopener,noreferrer");
        }
    }
};


// ===== sofia-htmleditor.js ===== 
window.sofiaHtmlEditor = {
    _registry: new Map(),

    init: function (editable, dotNetRef, id) {
        if (!editable) {
            return;
        }

        const state = { dotNetRef: dotNetRef, savedRange: null };

        const onSelectionChange = () => {
            const active = document.activeElement;
            if (active !== editable && !editable.contains(active)) {
                return;
            }

            const states = {};
            [
                "bold", "italic", "underline", "strikeThrough",
                "insertUnorderedList", "insertOrderedList",
                "justifyLeft", "justifyCenter", "justifyRight", "justifyFull"
            ].forEach(cmd => {
                try {
                    states[cmd] = document.queryCommandState(cmd);
                } catch (_) {
                    states[cmd] = false;
                }
            });

            dotNetRef.invokeMethodAsync("OnSelectionStateChanged", states).catch(() => {});
        };

        document.addEventListener("selectionchange", onSelectionChange);
        state.onSelectionChange = onSelectionChange;
        this._registry.set(id, state);
    },

    setHtml: function (editable, html) {
        if (editable) {
            editable.innerHTML = html || "";
        }
    },

    getHtml: function (editable) {
        return editable ? editable.innerHTML : "";
    },

    focus: function (editable) {
        if (editable) {
            editable.focus();
        }
    },

    saveSelection: function (id) {
        const state = this._registry.get(id);
        if (!state) {
            return;
        }

        const sel = window.getSelection();
        if (sel && sel.rangeCount > 0) {
            state.savedRange = sel.getRangeAt(0).cloneRange();
        }
    },

    restoreSelection: function (id, editable) {
        const state = this._registry.get(id);
        if (editable) {
            editable.focus();
        }

        if (!state || !state.savedRange) {
            return;
        }

        const sel = window.getSelection();
        sel.removeAllRanges();
        sel.addRange(state.savedRange);
    },

    // `restore` should be true only when focus left the editable region since the selection was
    // captured (e.g. a <select> or a popover input was used) — plain toolbar buttons prevent
    // mousedown default so the live selection is already correct and must NOT be overwritten
    // with a possibly-stale saved range.
    execCommand: function (editable, id, command, value, restore) {
        if (restore) {
            this.restoreSelection(id, editable);
        } else if (editable) {
            editable.focus();
        }

        try {
            document.execCommand(command, false, value ?? null);
        } catch (_) {
            /* unsupported in this browser — ignore */
        }

        return editable ? editable.innerHTML : "";
    },

    insertImageFile: async function (editable, id, fileInput, uploadUrl, headers) {
        const file = fileInput && fileInput.files && fileInput.files[0];
        if (!file) {
            return { success: false, url: null, html: editable ? editable.innerHTML : "" };
        }

        this.restoreSelection(id, editable);

        try {
            if (uploadUrl) {
                try {
                    const form = new FormData();
                    form.append("file", file);
                    const res = await fetch(uploadUrl, { method: "POST", body: form, headers: headers || {} });
                    if (res.ok) {
                        const data = await res.json().catch(() => null);
                        const url = data && (data.url || data.Url);
                        if (url) {
                            document.execCommand("insertImage", false, url);
                            return { success: true, url: url, html: editable ? editable.innerHTML : "" };
                        }
                    }
                } catch (_) {
                    /* fall through to failure result */
                }

                return { success: false, url: null, html: editable ? editable.innerHTML : "" };
            }

            const dataUrl = await new Promise((resolve, reject) => {
                const reader = new FileReader();
                reader.onload = () => resolve(reader.result);
                reader.onerror = reject;
                reader.readAsDataURL(file);
            });

            document.execCommand("insertImage", false, dataUrl);
            return { success: true, url: dataUrl, html: editable ? editable.innerHTML : "" };
        } catch (_) {
            return { success: false, url: null, html: editable ? editable.innerHTML : "" };
        } finally {
            fileInput.value = "";
        }
    },

    exportToPdf: function (html, title) {
        const iframe = document.createElement("iframe");
        iframe.style.position = "fixed";
        iframe.style.right = "0";
        iframe.style.bottom = "0";
        iframe.style.width = "0";
        iframe.style.height = "0";
        iframe.style.border = "0";
        iframe.setAttribute("aria-hidden", "true");
        document.body.appendChild(iframe);

        const cleanup = () => {
            setTimeout(() => {
                if (iframe.parentNode) {
                    iframe.parentNode.removeChild(iframe);
                }
            }, 1000);
        };

        const safeTitle = (title || "Document").replace(/[<>]/g, "");
        const doc = iframe.contentWindow.document;
        doc.open();
        doc.write(
            "<!doctype html><html><head><meta charset=\"utf-8\" /><title>" + safeTitle + "</title>" +
            "<style>" +
            "body{font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;color:#0f172a;padding:1.5rem;line-height:1.55;}" +
            "img{max-width:100%;}" +
            "table{border-collapse:collapse;width:100%;}" +
            "td,th{border:1px solid #cbd5e1;padding:0.35rem 0.6rem;}" +
            "blockquote{margin:0.75rem 0;padding-left:1rem;border-left:3px solid #cbd5e1;color:#475569;}" +
            "@media print { body { padding: 0; } }" +
            "</style></head><body>" + html + "</body></html>"
        );
        doc.close();

        const triggerPrint = () => {
            try {
                iframe.contentWindow.focus();
                iframe.contentWindow.print();
            } catch (_) {
                /* ignore */
            }

            cleanup();
        };

        if (doc.readyState === "complete") {
            triggerPrint();
        } else {
            iframe.onload = triggerPrint;
            setTimeout(triggerPrint, 400);
        }
    },

    dispose: function (id) {
        const state = this._registry.get(id);
        if (!state) {
            return;
        }

        document.removeEventListener("selectionchange", state.onSelectionChange);
        this._registry.delete(id);
    }
};


// ===== sofia-knob.js ===== 
window.sofiaKnob = {
    capture: function (element, pointerId) {
        if (!element || typeof element.setPointerCapture !== "function") {
            return;
        }

        try {
            element.setPointerCapture(pointerId);
        } catch (_) {
            /* ignore */
        }
    },

    release: function (element, pointerId) {
        if (!element || typeof element.releasePointerCapture !== "function") {
            return;
        }

        try {
            element.releasePointerCapture(pointerId);
        } catch (_) {
            /* ignore */
        }
    }
};


// ===== sofia-mask.js ===== 
window.sofiaMask = {
    setCaret: function (element, pos) {
        if (!element || typeof element.setSelectionRange !== "function") {
            return;
        }

        try {
            element.focus();
            element.setSelectionRange(pos, pos);
        } catch (_) {
            /* ignore selection errors on unsupported types */
        }
    }
};


// ===== sofia-mediaquery.js ===== 
window.sofiaMediaQuery = (function () {
    var entries = new Map();
    var nextId = 1;

    function bind(mql, handler) {
        if (typeof mql.addEventListener === "function") {
            mql.addEventListener("change", handler);
            return;
        }

        // Safari < 14
        mql.addListener(handler);
    }

    function unbind(mql, handler) {
        if (typeof mql.removeEventListener === "function") {
            mql.removeEventListener("change", handler);
            return;
        }

        mql.removeListener(handler);
    }

    return {
        observe: function (query, dotNetRef) {
            if (!query || typeof window.matchMedia !== "function" || !dotNetRef) {
                return 0;
            }

            var id = nextId++;
            var mql = window.matchMedia(query);
            var handler = function (event) {
                var matches = event && typeof event.matches === "boolean" ? event.matches : mql.matches;
                dotNetRef.invokeMethodAsync("OnMediaChange", matches);
            };

            bind(mql, handler);
            entries.set(id, { mql: mql, handler: handler });

            // Initial state
            dotNetRef.invokeMethodAsync("OnMediaChange", mql.matches);
            return id;
        },

        dispose: function (id) {
            var entry = entries.get(id);
            if (!entry) {
                return;
            }

            unbind(entry.mql, entry.handler);
            entries.delete(id);
        }
    };
})();


// ===== sofia-menu.js ===== 
window.sofiaMenu = {
    _handlers: {},

    open: function () { },

    position: function (popup, trigger, options) {
        if (!popup || !trigger) {
            return;
        }

        var side = (options && options.side) || "bottom";
        var align = (options && options.align) || "start";
        var sideOffset = (options && options.sideOffset) != null ? options.sideOffset : 4;
        var alignOffset = (options && options.alignOffset) != null ? options.alignOffset : 0;

        var tr = trigger.getBoundingClientRect();
        var pr = popup.getBoundingClientRect();
        var top = 0;
        var left = 0;

        if (side === "right") {
            left = tr.right + sideOffset;
            top = this._align(tr.top, tr.height, pr.height, align, alignOffset);
        } else if (side === "left") {
            left = tr.left - pr.width - sideOffset;
            top = this._align(tr.top, tr.height, pr.height, align, alignOffset);
        } else if (side === "top") {
            top = tr.top - pr.height - sideOffset;
            left = this._align(tr.left, tr.width, pr.width, align, alignOffset);
        } else {
            top = tr.bottom + sideOffset;
            left = this._align(tr.left, tr.width, pr.width, align, alignOffset);
        }

        var pad = 8;
        left = Math.min(Math.max(pad, left), window.innerWidth - pr.width - pad);
        top = Math.min(Math.max(pad, top), window.innerHeight - pr.height - pad);

        popup.style.position = "fixed";
        popup.style.top = Math.round(top) + "px";
        popup.style.left = Math.round(left) + "px";
        popup.style.visibility = "visible";
        popup.style.zIndex = "1160";
    },

    _align: function (origin, originSize, popupSize, align, alignOffset) {
        if (align === "center") {
            return origin + (originSize - popupSize) / 2 + alignOffset;
        }
        if (align === "end") {
            return origin + originSize - popupSize + alignOffset;
        }
        return origin + alignOffset;
    },

    attachDismiss: function (id, popup, trigger, dotNetRef) {
        this.detachDismiss(id);

        var handler = function (e) {
            var t = e.target;
            if (!popup || !trigger) {
                return;
            }
            if (popup.contains(t) || trigger.contains(t)) {
                return;
            }
            // Also keep open when interacting with nested submenu popups marked as sofia-menu__popup
            if (t.closest && t.closest(".sofia-ddmenu__popup")) {
                return;
            }
            dotNetRef.invokeMethodAsync("NotifyOutsideClick");
        };

        this._handlers[id] = handler;
        window.setTimeout(function () {
            document.addEventListener("mousedown", handler, true);
        }, 0);
    },

    detachDismiss: function (id) {
        var handler = this._handlers[id];
        if (!handler) {
            return;
        }
        if (typeof handler === "function") {
            document.removeEventListener("mousedown", handler, true);
        } else {
            if (handler.mousedown) {
                document.removeEventListener("mousedown", handler.mousedown, true);
            }
            if (handler.keydown) {
                document.removeEventListener("keydown", handler.keydown, true);
            }
        }
        delete this._handlers[id];
    },

    attachOutside: function (id, root, dotNetRef) {
        this.detachDismiss(id);

        var handler = function (e) {
            if (!root || root.contains(e.target)) {
                return;
            }
            if (e.target.closest && e.target.closest(".sofia-ddmenu__popup")) {
                return;
            }
            dotNetRef.invokeMethodAsync("NotifyOutsideClick");
        };

        this._handlers[id] = handler;
        window.setTimeout(function () {
            document.addEventListener("mousedown", handler, true);
        }, 0);
    },

    /** Position a popup at cursor coordinates (ContextMenu). */
    positionAtPoint: function (popup, clientX, clientY) {
        if (!popup) {
            return;
        }

        popup.style.position = "fixed";
        popup.style.left = "0px";
        popup.style.top = "0px";
        popup.style.visibility = "hidden";
        popup.style.zIndex = "1160";

        var pr = popup.getBoundingClientRect();
        var pad = 8;
        var left = clientX;
        var top = clientY;

        if (left + pr.width + pad > window.innerWidth) {
            left = clientX - pr.width;
        }
        if (top + pr.height + pad > window.innerHeight) {
            top = clientY - pr.height;
        }

        left = Math.min(Math.max(pad, left), window.innerWidth - pr.width - pad);
        top = Math.min(Math.max(pad, top), window.innerHeight - pr.height - pad);

        popup.style.left = Math.round(left) + "px";
        popup.style.top = Math.round(top) + "px";
        popup.style.visibility = "visible";
    },

    /**
     * ContextMenu dismiss: left-click outside + Escape (both optional via options).
     * options: { closeOnOutside: bool, closeOnEscape: bool }
     */
    attachDismissPoint: function (id, popup, root, dotNetRef, options) {
        this.detachDismiss(id);
        options = options || {};
        var closeOnOutside = options.closeOnOutside !== false;
        var closeOnEscape = options.closeOnEscape !== false;

        var onMouseDown = null;
        var onKeyDown = null;

        if (closeOnOutside) {
            onMouseDown = function (e) {
                // Primary (left) button only.
                if (e.button !== 0 || !popup) {
                    return;
                }
                var t = e.target;
                if (popup.contains(t)) {
                    return;
                }
                if (t.closest && t.closest(".sofia-ddmenu__popup")) {
                    return;
                }
                dotNetRef.invokeMethodAsync("NotifyOutsideClick");
            };
        }

        if (closeOnEscape) {
            onKeyDown = function (e) {
                if (e.key !== "Escape" && e.key !== "Esc") {
                    return;
                }
                e.preventDefault();
                e.stopPropagation();
                dotNetRef.invokeMethodAsync("NotifyEscape");
            };
        }

        this._handlers[id] = { mousedown: onMouseDown, keydown: onKeyDown };
        window.setTimeout(function () {
            if (onMouseDown) {
                document.addEventListener("mousedown", onMouseDown, true);
            }
            if (onKeyDown) {
                document.addEventListener("keydown", onKeyDown, true);
            }
        }, 0);
    },

    _globalHandlers: {},

    attachGlobalContextMenu: function (id, dotNetRef) {
        this.detachGlobalContextMenu(id);

        var handler = function (e) {
            e.preventDefault();
            dotNetRef.invokeMethodAsync("NotifyGlobalContextMenu", e.clientX, e.clientY);
        };

        this._globalHandlers[id] = handler;
        document.addEventListener("contextmenu", handler, true);
    },

    detachGlobalContextMenu: function (id) {
        var handler = this._globalHandlers[id];
        if (!handler) {
            return;
        }
        document.removeEventListener("contextmenu", handler, true);
        delete this._globalHandlers[id];
    }
};


// ===== sofia-otp.js ===== 
window.sofiaOtp = {
    focus: function (id) {
        var el = document.getElementById(id);
        if (!el) {
            return;
        }

        el.focus();
        if (typeof el.select === "function" && el.value) {
            el.select();
        }
    },

    readValue: function (id) {
        var el = document.getElementById(id);
        return el && el.value ? String(el.value) : "";
    }
};


// ===== sofia-popover.js ===== 
window.sofiaPopover = {
    _handlers: {},

    position: function (popup, trigger, options) {
        if (!popup || !trigger) {
            return;
        }

        var side = (options && options.side) || "bottom";
        var align = (options && options.align) || "start";
        var sideOffset = (options && options.sideOffset) != null ? options.sideOffset : 12;
        var alignOffset = (options && options.alignOffset) != null ? options.alignOffset : 0;
        var matchWidth = !!(options && options.matchWidth);
        var minWidth = (options && options.minWidth) != null ? options.minWidth : 0;

        var tr = trigger.getBoundingClientRect();

        // Width before measuring popup so flip/clamp uses the final size.
        if (matchWidth) {
            popup.style.width = Math.round(Math.max(tr.width, minWidth)) + "px";
            popup.style.right = "auto";
        }

        var pr = popup.getBoundingClientRect();
        var top = 0;
        var left = 0;

        if (side === "top") {
            top = tr.top - pr.height - sideOffset;
            left = this._alignMain(tr.left, tr.width, pr.width, align, alignOffset);
        } else if (side === "bottom") {
            top = tr.bottom + sideOffset;
            left = this._alignMain(tr.left, tr.width, pr.width, align, alignOffset);
        } else if (side === "left") {
            left = tr.left - pr.width - sideOffset;
            top = this._alignMain(tr.top, tr.height, pr.height, align, alignOffset);
        } else {
            left = tr.right + sideOffset;
            top = this._alignMain(tr.top, tr.height, pr.height, align, alignOffset);
        }

        var pad = 8;
        left = Math.min(Math.max(pad, left), window.innerWidth - pr.width - pad);
        top = Math.min(Math.max(pad, top), window.innerHeight - pr.height - pad);

        popup.style.position = "fixed";
        popup.style.top = Math.round(top) + "px";
        popup.style.left = Math.round(left) + "px";
        popup.style.visibility = "visible";
    },

    _alignMain: function (origin, originSize, popupSize, align, alignOffset) {
        if (align === "center") {
            return origin + (originSize - popupSize) / 2 + alignOffset;
        }

        if (align === "end") {
            return origin + originSize - popupSize + alignOffset;
        }

        return origin + alignOffset;
    },

    attachDismiss: function (id, popup, trigger, dotNetRef) {
        this.detachDismiss(id);

        var handler = function (e) {
            var t = e.target;
            if (!popup || !trigger) {
                return;
            }

            if (popup.contains(t) || trigger.contains(t)) {
                return;
            }

            dotNetRef.invokeMethodAsync("NotifyOutsideClick");
        };

        this._handlers[id] = handler;
        window.setTimeout(function () {
            document.addEventListener("mousedown", handler, true);
        }, 0);
    },

    detachDismiss: function (id) {
        var handler = this._handlers[id];
        if (!handler) {
            return;
        }

        document.removeEventListener("mousedown", handler, true);
        delete this._handlers[id];
    }
};


// ===== sofia-scrollarea.js ===== 
window.sofiaScrollArea = {
    getState: function (element) {
        if (!element) {
            return { atTop: true, atBottom: true, atLeft: true, atRight: true };
        }

        var top = element.scrollTop;
        var left = element.scrollLeft;
        var maxTop = Math.max(0, element.scrollHeight - element.clientHeight);
        var maxLeft = Math.max(0, element.scrollWidth - element.clientWidth);

        return {
            atTop: top <= 1,
            atBottom: top >= maxTop - 1,
            atLeft: left <= 1,
            atRight: left >= maxLeft - 1
        };
    }
};


// ===== sofia-signature.js ===== 
window.sofiaSignature = {
    _registry: new Map(),

    init: function (canvas, dotNetRef, options) {
        if (!canvas) {
            return;
        }

        const ctx = canvas.getContext("2d");
        const state = {
            ctx: ctx,
            dotNetRef: dotNetRef,
            options: options || {},
            drawing: false,
            points: [],
            hasInk: false,
            ratio: 1,
            ro: null
        };

        const strokeStyle = () => state.options.strokeColor || "#0f172a";
        const lineWidth = () => state.options.strokeWidth || 2;

        const redrawFromDataUrl = (dataUrl) => {
            if (!dataUrl) {
                return;
            }

            const img = new Image();
            img.onload = () => {
                const w = canvas.width / state.ratio;
                const h = canvas.height / state.ratio;
                ctx.clearRect(0, 0, w, h);
                ctx.drawImage(img, 0, 0, w, h);
            };
            img.src = dataUrl;
        };

        const resize = () => {
            const rect = canvas.getBoundingClientRect();
            if (rect.width <= 0 || rect.height <= 0) {
                return;
            }

            const prevDataUrl = state.hasInk ? canvas.toDataURL("image/png") : null;
            const ratio = window.devicePixelRatio || 1;
            state.ratio = ratio;
            canvas.width = Math.max(1, Math.round(rect.width * ratio));
            canvas.height = Math.max(1, Math.round(rect.height * ratio));
            ctx.setTransform(ratio, 0, 0, ratio, 0, 0);
            ctx.lineCap = "round";
            ctx.lineJoin = "round";
            redrawFromDataUrl(prevDataUrl);
        };

        resize();

        if (typeof ResizeObserver !== "undefined") {
            state.ro = new ResizeObserver(resize);
            state.ro.observe(canvas);
        }

        const getPoint = (e) => {
            const rect = canvas.getBoundingClientRect();
            return { x: e.clientX - rect.left, y: e.clientY - rect.top };
        };

        const drawSegment = (p0, p1, p2) => {
            ctx.strokeStyle = strokeStyle();
            ctx.lineWidth = lineWidth();
            ctx.beginPath();
            ctx.moveTo(p0.x, p0.y);
            const midX = (p1.x + p2.x) / 2;
            const midY = (p1.y + p2.y) / 2;
            ctx.quadraticCurveTo(p1.x, p1.y, midX, midY);
            ctx.stroke();
        };

        const drawDot = (p) => {
            ctx.beginPath();
            ctx.fillStyle = strokeStyle();
            ctx.arc(p.x, p.y, lineWidth() / 2, 0, Math.PI * 2);
            ctx.fill();
        };

        const onDown = (e) => {
            if (state.options.disabled || state.options.readOnly) {
                return;
            }

            state.drawing = true;
            state.hasInk = true;
            const p = getPoint(e);
            state.points = [p];
            drawDot(p);

            try {
                canvas.setPointerCapture(e.pointerId);
            } catch (_) {
                /* ignore */
            }

            e.preventDefault();
        };

        const onMove = (e) => {
            if (!state.drawing) {
                return;
            }

            const p = getPoint(e);
            state.points.push(p);
            const n = state.points.length;

            if (n === 2) {
                drawSegment(state.points[0], state.points[0], state.points[1]);
            } else if (n >= 3) {
                drawSegment(state.points[n - 3], state.points[n - 2], state.points[n - 1]);
            }

            e.preventDefault();
        };

        const endStroke = async (e) => {
            if (!state.drawing) {
                return;
            }

            state.drawing = false;

            try {
                canvas.releasePointerCapture(e.pointerId);
            } catch (_) {
                /* ignore */
            }

            if (!state.dotNetRef) {
                return;
            }

            const dataUrl = canvas.toDataURL("image/png");

            try {
                await state.dotNetRef.invokeMethodAsync("OnStrokeEnd", dataUrl);
            } catch (_) {
                /* component may already be disposed */
            }
        };

        canvas.addEventListener("pointerdown", onDown);
        canvas.addEventListener("pointermove", onMove);
        canvas.addEventListener("pointerup", endStroke);
        canvas.addEventListener("pointercancel", endStroke);

        state.handlers = { onDown: onDown, onMove: onMove, endStroke: endStroke };
        this._registry.set(canvas, state);
    },

    setOptions: function (canvas, options) {
        const state = this._registry.get(canvas);
        if (state) {
            state.options = options || {};
        }
    },

    setValue: function (canvas, dataUrl) {
        const state = this._registry.get(canvas);
        if (!state) {
            return;
        }

        state.hasInk = !!dataUrl;
        const w = canvas.width / state.ratio;
        const h = canvas.height / state.ratio;
        state.ctx.clearRect(0, 0, w, h);

        if (!dataUrl) {
            return;
        }

        const img = new Image();
        img.onload = () => state.ctx.drawImage(img, 0, 0, w, h);
        img.src = dataUrl;
    },

    clear: function (canvas) {
        const state = this._registry.get(canvas);
        if (!state) {
            return;
        }

        state.hasInk = false;
        const w = canvas.width / state.ratio;
        const h = canvas.height / state.ratio;
        state.ctx.clearRect(0, 0, w, h);
    },

    dispose: function (canvas) {
        const state = this._registry.get(canvas);
        if (!state) {
            return;
        }

        canvas.removeEventListener("pointerdown", state.handlers.onDown);
        canvas.removeEventListener("pointermove", state.handlers.onMove);
        canvas.removeEventListener("pointerup", state.handlers.endStroke);
        canvas.removeEventListener("pointercancel", state.handlers.endStroke);

        if (state.ro) {
            state.ro.disconnect();
        }

        this._registry.delete(canvas);
    }
};


// ===== sofia-slider.js ===== 
window.sofiaSlider = {
    ratio: function (element, clientX, clientY, vertical) {
        if (!element || typeof element.getBoundingClientRect !== "function") {
            return 0;
        }

        var rect = element.getBoundingClientRect();
        if (!rect.width || !rect.height) {
            return 0;
        }

        if (vertical) {
            return Math.min(1, Math.max(0, 1 - (clientY - rect.top) / rect.height));
        }

        return Math.min(1, Math.max(0, (clientX - rect.left) / rect.width));
    },

    capture: function (element, pointerId) {
        if (!element || typeof element.setPointerCapture !== "function") {
            return;
        }

        try {
            element.setPointerCapture(pointerId);
        } catch (_) {
            /* ignore */
        }
    },

    release: function (element, pointerId) {
        if (!element || typeof element.releasePointerCapture !== "function") {
            return;
        }

        try {
            element.releasePointerCapture(pointerId);
        } catch (_) {
            /* ignore */
        }
    }
};


// ===== sofia-speech.js ===== 
window.sofiaSpeech = {
    _registry: new Map(),

    isSupported: function () {
        return !!(window.SpeechRecognition || window.webkitSpeechRecognition);
    },

    start: function (dotNetRef, id, language) {
        const Ctor = window.SpeechRecognition || window.webkitSpeechRecognition;
        if (!Ctor) {
            return false;
        }

        this.stop(id);

        const recognition = new Ctor();
        recognition.lang = language || navigator.language || "en-US";
        recognition.continuous = true;
        recognition.interimResults = false;

        let finalTranscript = "";

        recognition.onresult = function (event) {
            for (let i = event.resultIndex; i < event.results.length; i++) {
                if (event.results[i].isFinal) {
                    finalTranscript += event.results[i][0].transcript;
                }
            }
        };

        recognition.onerror = function () {
            /* swallowed — onend still fires and finalizes with whatever transcript was captured */
        };

        recognition.onend = async () => {
            this._registry.delete(id);

            try {
                await dotNetRef.invokeMethodAsync("OnResult", finalTranscript.trim());
            } catch (_) {
                /* component may already be disposed */
            }
        };

        try {
            recognition.start();
        } catch (_) {
            return false;
        }

        this._registry.set(id, recognition);
        return true;
    },

    stop: function (id) {
        const recognition = this._registry.get(id);
        if (!recognition) {
            return;
        }

        try {
            recognition.stop();
        } catch (_) {
            /* ignore */
        }
    },

    dispose: function (id) {
        this.stop(id);
        this._registry.delete(id);
    }
};


// ===== sofia-speeddial.js ===== 
window.sofiaSpeedDial = {
    _handlers: new WeakMap(),

    attachOutside: function (element, dotNetRef) {
        if (!element || !dotNetRef) {
            return;
        }

        this.detachOutside(element);

        var pointerHandler = function (event) {
            if (element.contains(event.target)) {
                return;
            }

            dotNetRef.invokeMethodAsync("OnOutsideClick");
        };

        var keyHandler = function (event) {
            if (event.key === "Escape") {
                dotNetRef.invokeMethodAsync("OnOutsideClick");
            }
        };

        document.addEventListener("pointerdown", pointerHandler, true);
        document.addEventListener("keydown", keyHandler, true);
        this._handlers.set(element, { pointerHandler: pointerHandler, keyHandler: keyHandler });
    },

    detachOutside: function (element) {
        if (!element) {
            return;
        }

        var handlers = this._handlers.get(element);
        if (!handlers) {
            return;
        }

        document.removeEventListener("pointerdown", handlers.pointerHandler, true);
        document.removeEventListener("keydown", handlers.keyHandler, true);
        this._handlers.delete(element);
    }
};


// ===== sofia-splitbutton.js ===== 
window.sofiaSplitButton = {
    _handlers: new WeakMap(),

    attachOutside: function (element, dotNetRef) {
        if (!element || !dotNetRef) {
            return;
        }

        this.detachOutside(element);

        var pointerHandler = function (event) {
            if (element.contains(event.target)) {
                return;
            }

            dotNetRef.invokeMethodAsync("OnOutsideClick");
        };

        var keyHandler = function (event) {
            if (event.key === "Escape") {
                dotNetRef.invokeMethodAsync("OnOutsideClick");
            }
        };

        document.addEventListener("pointerdown", pointerHandler, true);
        document.addEventListener("keydown", keyHandler, true);
        this._handlers.set(element, { pointerHandler: pointerHandler, keyHandler: keyHandler });
    },

    detachOutside: function (element) {
        if (!element) {
            return;
        }

        var handlers = this._handlers.get(element);
        if (!handlers) {
            return;
        }

        document.removeEventListener("pointerdown", handlers.pointerHandler, true);
        document.removeEventListener("keydown", handlers.keyHandler, true);
        this._handlers.delete(element);
    }
};


// ===== sofia-splitter.js ===== 
window.sofiaSplitter = {
    measure: function (element, vertical) {
        if (!element || typeof element.getBoundingClientRect !== "function") {
            return { size: 0, start: 0 };
        }

        var rect = element.getBoundingClientRect();
        return vertical
            ? { size: rect.height, start: rect.top }
            : { size: rect.width, start: rect.left };
    },

    capture: function (element, pointerId) {
        if (!element || typeof element.setPointerCapture !== "function") {
            return;
        }

        try {
            element.setPointerCapture(pointerId);
        } catch (_) {
            /* ignore */
        }
    },

    release: function (element, pointerId) {
        if (!element || typeof element.releasePointerCapture !== "function") {
            return;
        }

        try {
            element.releasePointerCapture(pointerId);
        } catch (_) {
            /* ignore */
        }
    }
};


// ===== sofia-tabs.js ===== 
window.sofiaTabs = {
    scrollBy: function (element, delta) {
        if (!element) {
            return;
        }

        element.scrollBy({ left: delta, behavior: "smooth" });
    },

    scrollIntoView: function (list, tab) {
        if (!list || !tab || typeof tab.scrollIntoView !== "function") {
            return;
        }

        tab.scrollIntoView({ behavior: "smooth", inline: "nearest", block: "nearest" });
    },

    canScroll: function (element) {
        if (!element) {
            return { left: false, right: false };
        }

        var max = Math.max(0, element.scrollWidth - element.clientWidth);
        return {
            left: element.scrollLeft > 1,
            right: element.scrollLeft < max - 1
        };
    }
};


// ===== sofia-textarea.js ===== 
window.sofiaTextarea = {
    autoResize: function (element) {
        if (!element) {
            return;
        }

        element.style.height = "auto";
        element.style.height = element.scrollHeight + "px";
    }
};


// ===== sofia-tilelayout.js ===== 
window.sofiaTileLayout = {
    _observers: new WeakMap(),

    observe: function (element, dotNetRef) {
        if (!element || typeof ResizeObserver === "undefined") {
            return;
        }

        this.unobserve(element);

        var notify = function () {
            var rect = element.getBoundingClientRect();
            dotNetRef.invokeMethodAsync("OnHostResized", rect.width, rect.height);
        };

        var ro = new ResizeObserver(function () {
            notify();
        });

        ro.observe(element);
        this._observers.set(element, { ro: ro, dotNetRef: dotNetRef });
        notify();
    },

    unobserve: function (element) {
        if (!element) {
            return;
        }

        var entry = this._observers.get(element);
        if (!entry) {
            return;
        }

        try {
            entry.ro.disconnect();
        } catch (_) {
            /* ignore */
        }

        this._observers.delete(element);
    }
};


